### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by skuzzymiglet** [Alligator/termbox-janet#1]
https://github.com/sepisoad/jtbox uses the name `termbox` as well as this package. Janet does not handle name conflicts like this very well. What do you propose as a solution?

**Comment by Alligator** [comment]
ah. if I knew that existed I probably wouldn't have created these bindings to begin with.

I'm fine with renaming this package, since jtbox was there first.

**Comment by pepe** [comment]
I think your implementation is nicer, TBH.

It is probably my fault, too, as the packages are not easily searchable or transparent at all. 

I think this is a good case for finally starting some more advanced packages repository transparency.

**Comment by Alligator** [comment]
Packages being searchable would definitely help... although I do have my own script to scrape package GitHub descriptions and I didn't think to search for termbox :/
```
~/c/janet $ janet pkg-descs.janet | rg -i termbox
GitHub - sepisoad/jtbox: Janet wrapper around termbox
```

**Comment by sogaiu** [comment]
On a side note, there are a few lists around of existing janet projects: https://gist.github.com/felixr/5302f3f80b0510b402b8eaffa96dc77b
